---
- name: Ensure {{ ssl_group }} group exists
  group:
    name: "{{ ssl_group }}"
    state: present

- name: Add users to {{ ssl_group }} group
  user:
    name: "{{ item }}"
    groups: "{{ ssl_group }}"
    append: yes
  with_items: "{{ ssl_users }}"

- name: Create DB SSL directory
  file:
    path: "{{ item }}"
    state: directory
    mode: '0770'
    owner: root
    group: "{{ ssl_group }}"
  with_items:
    - "{{ ssl_certs_dir }}"
    - "{{ ssl_private_key_dir }}"

- name: Copy letsencrypt key and crt
  include_tasks: letsencrypt.yml
  when: ssl[(domain_name + '_crt')] is undefined

- name: Add ssl key and ssl crt
  include_tasks: add_ssl_content.yml
  when: ssl[(domain_name + '_crt')] is defined
